### ISSUE TITLE
Support RLP encoding/decoding

### ISSUE THREAD

**Issue by ImJeremyHe** [EspressoSystems/espresso-sequencer-go#16]

**Comment by sveitser** [comment]
@ImJeremyHe please add details on what needs to be done here. It would be good to do this earlier rather than later otherwise we need to maintain backwards compatibility.

**Comment by ImJeremyHe** [comment]
This issue was because we needed to encode types into RLP previously. This isn't an issue anymore and users don't suppose to encode/decode the espresso go types in RLP.
